name: 'Update to Latest Lambda Layers'
description: 'Update the AWS lambda layers for a given function to their latest versions'
inputs:
  function_name:
    description: 'The lambda function name'
    required: true
  aws_access_key_id:
    description: 'The AWS access key id for an IAM user'
    required: true
  aws_secret_access_key:
    description: 'The AWS secret access key for an IAM user'
    required: true
  aws_region:
    description: 'The AWS region the lambda function is located in'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
